version: '3.1'

services:

 wordpress:
   image: wordpress
   restart: always
   ports:
     - 8080:80
   environment:
     WORDPRESS_DB_HOST: db
     WORDPRESS_DB_USER: exampleuser
     WORDPRESS_DB_PASSWORD: examplepass
     WORDPRESS_DB_NAME: exampledb
   # Keep your data
   volumes: 
     - ./site:/var/www/html/
 
 cli:
   image: wordpress:cli
   volumes:
     - ./site:/var/www/html/

 db:
   image: mysql:5.7
   restart: always
   environment:
     MYSQL_DATABASE: exampledb
     MYSQL_USER: exampleuser
     MYSQL_PASSWORD: examplepass
     MYSQL_RANDOM_ROOT_PASSWORD: '1'
   # Keep your data
   volumes: 
     - ./db:/var/lib/mysql
